### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crimilo** [TreyRuffy/CommandBlocker#2]
[22:16:42 INFO]: [Command Blocker] Enabling CommandBlocker v5.4
[22:16:42 ERROR]: Error occurred while enabling CommandBlocker v5.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
        at me.treyruffy.commandblocker.Updater.UpdateChecker.getLastUpdate(UpdateChecker.java:19) ~[?:?]
        at me.treyruffy.commandblocker.Updater.Updates.updateCheck(Updates.java:18) ~[?:?]
        at me.treyruffy.commandblocker.CommandBlocker.onEnable(CommandBlocker.java:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
        ... 14 more

**Comment by TreyRuffy** [comment]
I am about to fix this right now! It should come out on the Spigot forums in a couple of minutes.
