### ISSUE TITLE
Errors in version 1.18.2. Please update plagin

### ISSUE THREAD

**Issue by Kotarych** [TreyRuffy/CommandBlocker#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Server Type: [e.g. Spigot, BungeeCord, Paper]
 - Version [e.g. 1.8.9, 1.16.2]

**Additional context**

**Comment by CatPeach** [comment]
Same, these console error on purpur 1.18.2 server:
`[02:59:34]` [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandBlocker v2.1.1
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
	at me.treyruffy.commandblocker.bukkit.Variables.translateVariables(Variables.java:57) ~[CommandBlockerFull-2.1.1.jar:?]
	at me.treyruffy.commandblocker.bukkit.Variables.translateVariables(Variables.java:66) ~[CommandBlockerFull-2.1.1.jar:?]
	at me.treyruffy.commandblocker.bukkit.Variables.translateVariablesToLegacyString(Variables.java:84) ~[CommandBlockerFull-2.1.1.jar:?]
	at me.treyruffy.commandblocker.bukkit.gui.DisabledGui.onInventoryClick(DisabledGui.java:334) ~[CommandBlockerFull-2.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor232.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1586]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2937) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1428) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1405) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1258) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1586]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by TreyRuffy** [comment]
I am in the process of updating it but it is taking a little longer than expected.

**Comment by TreyRuffy** [comment]
Closed. Download v2.1.2 to fix the bug
